### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AntoineTurmel** [AmarOk1412/Flyer-MozFr#1]
Quelques petites suggestions :
- Première section du front : mettre "mozilla" en blanc plutôt qu'en orange (le logo est plutôt utilisé en gris/blanc/rouge, le orange étant réservé à Firefox plutôt
- "Ne pas jeter sur la voie publique" en moins gros, et peut être à la verticale ? C'est pas tellement un contenu, plutôt une indication annexe

Sinon beau boulot :) Tu fait ça avec quel logiciel ?

**Comment by AmarOk1412** [comment]
+1 pour le mozilla en blanc et pour le pas jeter en plus petit. Par contre à la verticale ça risque de trop casser je pense.
Sinon j'ai fait ça avec the gimp

**Comment by AmarOk1412** [comment]
![frontt](https://cloud.githubusercontent.com/assets/1888628/6430084/617d04d0-bffb-11e4-8149-28b7f7f2e6d7.jpg)
Mieux ?

**Comment by AntoineTurmel** [comment]
nickel :)

**Comment by AmarOk1412** [comment]
thx :)
